"""initial revision

Revision ID: 5f79406514b0
Revises: 015f5ab4e4db
Create Date: 2023-09-17 21:46:39.826103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f79406514b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('team', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, default= None),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('headquarters', sa.String(length=100), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    )



    op.create_table('hero',sa.Column('id',sa.Integer(),autoincrement=True,nullable=False),
    sa.Column('name',sa.String(length=50),nullable=True),
    sa.Column('secret_name',sa.String(length=50),nullable=True),
    sa.Column('age',sa.Integer(),nullable=True),
    sa.Column('team_id',sa.Integer(),nullable=True),
    sa.ForeignKeyConstraint(['team_id'],['team.id'],),
    sa.PrimaryKeyConstraint('id'),
                   )



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('hero')
    # ### end Alembic commands ###
