"""roles and users with extra fields

Revision ID: fb6b6a36c433
Revises: 18ebeb04ef58
Create Date: 2023-09-26 12:38:49.447700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6b6a36c433'
down_revision = '18ebeb04ef58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_name', sa.VARCHAR(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'))
    op.create_table('roles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('role_name', sa.VARCHAR(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id', name='roles_pkey'))
    op.create_table('user_roles', sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('role_id', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_roles_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_users_id_fkey'), )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('roles')
    op.drop_table('users')
    # ### end Alembic commands ###
