"""sunroof column added in car

Revision ID: 43ddc52023e3
Revises: c49483b96465
Create Date: 2023-06-10 17:33:16.733670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ddc52023e3'
down_revision = 'c49483b96465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('is_sunroof', sa.Boolean(), nullable=True))
    # op.drop_index('ix_car_model', table_name='car')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_car_model', 'car', ['model'], unique=False)
    op.drop_column('car', 'is_sunroof')
    # ### end Alembic commands ###
