"""Heros & Teams

Revision ID: c190db6ddc7a
Revises: ebe75b75d42f
Create Date: 2023-08-04 12:43:52.164459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c190db6ddc7a'
down_revision = 'ebe75b75d42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('book')
    op.drop_index('ix_car_model', table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('make', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_sunroof', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='car_pkey'),
    sa.UniqueConstraint('model', name='car_model_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_car_model', 'car', ['model'], unique=False)
    op.create_table('book',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    op.create_table('person',
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('country_of_birth', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('car_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name='person_car_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_pkey'),
    sa.UniqueConstraint('car_id', name='person_car_id_key'),
    sa.UniqueConstraint('email', name='person_email_unique')
    )
    # ### end Alembic commands ###
