"""index added

Revision ID: c49483b96465
Revises: 0c4e279ce589
Create Date: 2023-06-10 17:28:28.478253

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "c49483b96465"
down_revision = "0c4e279ce589"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(index_name="ix_car_model", table_name="car", columns=["model"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(index_name="ix_car_model")
    # ### end Alembic commands ###
